[package]
name = "vxl"
version = "0.6.0"
edition = "2024"
license-file = "LICENSE"
repository = "https://github.com/tyleo/tyt"
description = "A command-line tool for working with voxels."
exclude = ["trials"]
autobins = false

[package.metadata.workspaces]
independent = true

[[bin]]
name = "vxl"
path = "src/main.rs"
required-features = ["bin"]

[dependencies]
branded-id = "0.2.0"
clap = { version = "4.5.58", features = ["derive"] }
crossterm = "0.29"
image = { version = "0.25", default-features = false }
jsonc-parser = { version = "0.33.1", features = ["serde"] }
meshconv = "0.3.0"
meshdoc = "0.3.0"
sdfconv = "0.2.0"
sdfj = "0.2.0"
sdfj-builder = "0.3.0"
sdfj-codec = "0.2.0"
sdfj-sdfcore = "0.2.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tempfile = "3.27"
ty-clap = { version = "0.1.0", optional = true }
ty-math = "0.4.0"
ty-preferences = "0.4.0"
viuer = "0.11"
vox-value-language = "0.2.0"
voxconv = "0.3.0"
voxcore = { version = "0.4.0", default-features = false }
voxsmith = { version = "0.6.0", default-features = false, features = [
    "impl",
    "mesh_doc",
    "node",
    "object",
    "palette",
    "profile",
    "render",
    "sdf_doc",
    "vox_doc",
] }

[dev-dependencies]
ty-math = { version = "0.4.0", default-features = false }

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[features]
bin = ["dep:ty-clap"]
