[package]
name = "voxsmith"
version = "0.5.0"
edition = "2024"
license-file = "LICENSE"
repository = "https://github.com/tyleo/tyt"
description = "Utilities for working with voxels."

[package.metadata.workspaces]
independent = true

[package.metadata.docs.rs]
all-features = true

[dependencies]
branded-id = "0.2.0"
meshdoc = "0.3.0"
pathspec = "0.3.0"
png = { version = "0.18.1", optional = true }
sdfcore = { version = "0.2.0", optional = true }
serde_json = { version = "1", optional = true }
treegrid = { version = "0.4.0", features = [
    "json",
    "ty-math",
], optional = true }
treeselect = { version = "0.2.0", optional = true }
ty-math = "0.4.0"
vox-value-language = { version = "0.2.0", optional = true }
voxcore = { version = "0.4.0", default-features = false, features = ["color"] }
voxrender = { version = "0.3.0", optional = true }
voxsurface = { version = "0.3.0", optional = true }
zune-jpeg = { version = "0.5", optional = true }

[features]
default = [
    "impl",
    "mesh_doc",
    "node",
    "object",
    "palette",
    "profile",
    "render",
    "sdf_doc",
    "vox_doc",
]

mesh_doc = []
node = ["_treegrid", "dep:treeselect"]
object = ["dep:serde_json", "dep:vox-value-language", "dep:voxsurface"]
palette = ["_treegrid", "dep:serde_json", "dep:vox-value-language"]
profile = ["_treegrid"]
render = ["object", "dep:voxrender"]
sdf_doc = ["dep:sdfcore"]
vox_doc = ["_treegrid"]

impl = ["dep:png", "dep:zune-jpeg"]

_treegrid = ["dep:treegrid"]

[dev-dependencies]
png = "0.18"
